CC = gcc -Wall 
LIB = myAlloc
OUTNAME = zad1
MAIN = main


run_shared: shared
		./$(OUTNAME)_shared 128 256 1 1 15

run_dynamic: dynamic
		./$(OUTNAME)_dynamic

run_static: static
		./$(OUTNAME)_static




		
shared:

	# zbuduj biblioteke wspoldzielona .so
	$(CC) -fPIC -c $(LIB).c -o $(LIB).o
	$(CC) -fPIC -shared -o lib$(LIB).so $(LIB).o

	# linkowanie
	$(CC) -Wl,-rpath=. -L. -o $(OUTNAME)_shared $(MAIN).c -l$(LIB)

	# czyscimy
	rm -f *.o
		
		

static:
	# kompilacja zrodla
	$(CC) -c $(LIB).c -o $(LIB).o

	# zbuduj biblioteke statyczna .a
	ar rcs lib$(LIB).a $(LIB).o

	# linkowanie
	$(CC) -static $(MAIN).c -L. -l$(LIB) -o $(OUTNAME)_static

	# czyscimy
	rm -f *.o	


dynamic:
	# zbuduj biblioteke wspoldzielona .so
	$(CC) -fPIC -c $(LIB).c -o $(LIB).o
	$(CC) -Wl,-rpath=. -fPIC -shared -o lib$(LIB).so $(LIB).o

	# linkowanie
	$(CC) -L. -o $(OUTNAME)_dynamic $(MAIN).c -ldl -D DLL

	# czyscimy
	rm -f*.0

#clean:
	rm -f *.o
		